### ISSUE TITLE
Add OpenRA/ra2 to the GitHub feed

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/Orabot#23]
Submissions to https://github.com/OpenRA/ra2 are often overlooked.

**Comment by penev92** [comment]
This isn't done via the bot, so I can't help here.
#43 added ra2's repository to the list of parsed GH issue numbers, so the bot supports that. The Discord feed is based on a direct GitHub-Discord integration that involves @pchote and @jaZzKCS, but not me or orabot.
