### ISSUE TITLE
Advertise new maps in #mapmaking

### ISSUE THREAD

**Issue by jaZzKCS** [OpenRA/Orabot#25]
The IRC bot has it.

[21:19] | orabot | New map: Argal by Super Newbie - https://resource.openra.net/maps/34556/

As a link to the resource centre in the same veins as the github notifications.

**Comment by Mailaender** [comment]
I came up with https://github.com/OpenHV/HardVacuumRobot/blob/main/HardVacuumRobot/ResourceCenter.cs which is a direct port of https://github.com/ihptru/orabot/blob/master/tools/new_map.py

**Comment by penev92** [comment]
Done in #56.
